# Generated by Django 6.1.1 on 2026-10-05 10:17

import accounts.validators
import django.db.models.deletion
import recruitments.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('required_skills', models.TextField(blank=True)),
                ('min_experience_months', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('accepted_rows', models.PositiveIntegerField(default=0)),
                ('rejected_rows', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='application_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20, validators=[accounts.validators.validate_phone_format])),
                ('college', models.CharField(max_length=200)),
                ('skills', models.TextField(blank=True)),
                ('experience_months', models.IntegerField(default=0, validators=[recruitments.validators.validate_non_negative])),
                ('notice_period_days', models.IntegerField(default=0, validators=[recruitments.validators.validate_non_negative])),
                ('expected_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[recruitments.validators.validate_non_negative])),
                ('resume_text', models.TextField(blank=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('resume_file', models.FileField(blank=True, upload_to='resumes/')),
                ('profile_image', models.ImageField(blank=True, upload_to='images/')),
                ('historical_selection_status', models.CharField(blank=True, max_length=50)),
                ('screening_status', models.CharField(choices=[('PENDING', 'Pending'), ('SHORTLISTED', 'Shortlisted'), ('WAITLISTED', 'Waitlisted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_candidates', to=settings.AUTH_USER_MODEL)),
                ('applied_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidates', to='recruitments.jobrole')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScreeningResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SHORTLISTED', 'Shortlisted'), ('WAITLISTED', 'Waitlisted'), ('REJECTED', 'Rejected')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='screening_result', to='recruitments.candidate')),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['email'], name='recruitment_email_4f3dc5_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['applied_role', 'screening_status'], name='recruitment_applied_1d19e8_idx'),
        ),
    ]
